-- Lote 0-7: ciclo de piloto cerrado y capacidades simuladas/fail-closed.
-- No habilita documentos reales, IA externa, comunicaciones externas, pagos reales ni PRD_2026.

begin;

create table if not exists public.feature_flag_registry (
  code text primary key,
  enabled boolean not null default false,
  locked_closed boolean not null default true,
  reason text not null,
  updated_at timestamptz not null default now(),
  check (code in (
    'REAL_DOCUMENTS',
    'EXTERNAL_OCR_AI',
    'EXTERNAL_COMMUNICATIONS',
    'REAL_PAYMENTS',
    'REAL_HUMAN_REVIEW',
    'REAL_PERSONAL_DATA',
    'PRD_2026'
  )),
  check (locked_closed or enabled = false)
);

create table if not exists public.pilot_participants (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.app_users(id) on delete cascade,
  invitation_code text not null unique,
  state text not null default 'invited'
    check (state in ('invited', 'accepted', 'active', 'withdrawn', 'deletion_requested', 'suspended', 'deleted')),
  accepted_privacy_version text,
  suspended_cause text
    check (suspended_cause is null or suspended_cause in (
      'participant_withdrawal',
      'deletion_request',
      'suspected_real_personal_data',
      'real_document_uploaded',
      'external_provider_enabled',
      'payment_attempt_real',
      'legal_contradiction_detected',
      'admin_privilege_violation',
      'cross_user_access_attempt',
      'prd_2026_activation_attempt'
    )),
  invited_at timestamptz not null default now(),
  accepted_at timestamptz,
  withdrawn_at timestamptz,
  deleted_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (user_id)
);

create table if not exists public.pilot_events (
  id bigint generated by default as identity primary key,
  participant_id uuid not null references public.pilot_participants(id) on delete cascade,
  actor_user_id uuid references public.app_users(id) on delete set null,
  event_type text not null,
  event_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.diagnostic_runs (
  id uuid primary key default gen_random_uuid(),
  case_id uuid references public.cases(id) on delete cascade,
  user_id uuid references public.app_users(id) on delete set null,
  version text not null,
  input_payload jsonb not null,
  result_payload jsonb not null,
  source_basis text not null,
  requires_human_review boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.checklist_versions (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references public.cases(id) on delete cascade,
  version text not null,
  generated_from_diagnostic_id uuid references public.diagnostic_runs(id) on delete set null,
  superseded_by uuid references public.checklist_versions(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (case_id, version, created_at)
);

create table if not exists public.checklist_items (
  id uuid primary key default gen_random_uuid(),
  checklist_version_id uuid not null references public.checklist_versions(id) on delete cascade,
  item_code text not null,
  category text not null check (category in ('identity', 'academic', 'legalization', 'administrative', 'review')),
  title text not null,
  applicable boolean not null,
  required boolean not null,
  status text not null default 'missing'
    check (status in ('missing', 'prepared', 'uploaded_fictitious', 'not_applicable', 'needs_review')),
  preparation text not null,
  compliance_modes jsonb not null default '[]'::jsonb,
  explanation text not null,
  source_basis text not null,
  created_at timestamptz not null default now(),
  unique (checklist_version_id, item_code)
);

alter table public.documents add column if not exists immutable_version_id uuid default gen_random_uuid();
alter table public.documents add column if not exists quarantine_state text not null default 'not_quarantined'
  check (quarantine_state in ('not_quarantined', 'quarantined_simulated', 'released_simulated', 'purged'));
alter table public.documents add column if not exists blocked_at timestamptz;
alter table public.documents add column if not exists purged_at timestamptz;

create table if not exists public.document_processing_evidence (
  id uuid primary key default gen_random_uuid(),
  document_id uuid references public.documents(id) on delete cascade,
  job_id uuid references public.processing_jobs(id) on delete set null,
  stage text not null check (stage in ('technical_check', 'ocr', 'deterministic_rules', 'ai', 'human_review')),
  provider text not null default 'local-simulator',
  status text not null check (status in ('queued', 'running', 'succeeded', 'failed', 'revoked')),
  confidence numeric(5,4) check (confidence is null or (confidence >= 0 and confidence <= 1)),
  evidence_payload jsonb not null default '{}'::jsonb,
  idempotency_key text not null,
  revoked_at timestamptz,
  created_at timestamptz not null default now(),
  unique (stage, idempotency_key)
);

create table if not exists public.presentation_guides (
  id uuid primary key default gen_random_uuid(),
  code text not null,
  version text not null,
  title text not null,
  variable_data jsonb not null default '{}'::jsonb,
  source_url text not null,
  source_verified_at timestamptz not null,
  valid_from date not null,
  valid_until date,
  status text not null default 'active' check (status in ('active', 'expired', 'superseded')),
  created_at timestamptz not null default now(),
  unique (code, version)
);

create table if not exists public.tracking_tasks (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references public.cases(id) on delete cascade,
  task_type text not null check (task_type in ('milestone', 'rectification', 'subsanation', 'internal_notice')),
  title text not null,
  description text not null,
  status text not null default 'open' check (status in ('open', 'done', 'cancelled', 'blocked')),
  legal_effect_blocked boolean not null default true,
  created_by uuid references public.app_users(id) on delete set null,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.admin_action_history (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references public.app_users(id) on delete set null,
  target_user_id uuid references public.app_users(id) on delete set null,
  action text not null,
  minimum_privilege_role text not null check (minimum_privilege_role in ('USER', 'ADVISOR', 'ADMIN')),
  requires_second_approval boolean not null default false,
  second_approval_user_id uuid references public.app_users(id) on delete set null,
  result text not null default 'success' check (result in ('success', 'denied', 'failed')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.service_catalog (
  code text primary key,
  name_es text not null,
  description text not null,
  price_cents integer not null check (price_cents >= 0),
  currency char(3) not null default 'EUR',
  fictitious boolean not null default true,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.payment_transactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.app_users(id) on delete set null,
  case_id uuid references public.cases(id) on delete set null,
  service_code text references public.service_catalog(code) on delete restrict,
  provider text not null default 'polar-simulator',
  provider_reference text not null,
  idempotency_key text not null unique,
  amount_cents integer not null check (amount_cents >= 0),
  currency char(3) not null,
  status text not null check (status in (
    'draft',
    'simulated_authorized',
    'simulated_captured',
    'simulated_refunded',
    'simulated_disputed',
    'blocked_real_payment'
  )),
  webhook_payload jsonb not null default '{}'::jsonb,
  reconciled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists pilot_participants_state_idx on public.pilot_participants(state);
create index if not exists pilot_events_participant_id_idx on public.pilot_events(participant_id, created_at desc);
create index if not exists diagnostic_runs_case_id_idx on public.diagnostic_runs(case_id, created_at desc);
create index if not exists checklist_versions_case_id_idx on public.checklist_versions(case_id, created_at desc);
create index if not exists checklist_items_version_idx on public.checklist_items(checklist_version_id);
create index if not exists document_processing_evidence_document_id_idx on public.document_processing_evidence(document_id, created_at desc);
create index if not exists tracking_tasks_case_id_idx on public.tracking_tasks(case_id, created_at desc);
create index if not exists payment_transactions_case_id_idx on public.payment_transactions(case_id, created_at desc);

drop trigger if exists pilot_participants_set_updated_at on public.pilot_participants;
create trigger pilot_participants_set_updated_at before update on public.pilot_participants
for each row execute function public.set_updated_at();

drop trigger if exists payment_transactions_set_updated_at on public.payment_transactions;
create trigger payment_transactions_set_updated_at before update on public.payment_transactions
for each row execute function public.set_updated_at();

insert into public.feature_flag_registry (code, enabled, locked_closed, reason)
values
  ('REAL_DOCUMENTS', false, true, 'Documentos reales cerrados hasta revision de privacidad y lanzamiento formal.'),
  ('EXTERNAL_OCR_AI', false, true, 'OCR e IA externos desactivados; solo simuladores o procesamiento local ficticio.'),
  ('EXTERNAL_COMMUNICATIONS', false, true, 'Comunicaciones externas desactivadas sin dominio, DPA y consentimiento operativo.'),
  ('REAL_PAYMENTS', false, true, 'Cobros reales y facturacion real cerrados; usar adaptador simulado.'),
  ('REAL_HUMAN_REVIEW', false, true, 'Revision humana real cerrada hasta gobierno operacional aprobado.'),
  ('REAL_PERSONAL_DATA', false, true, 'Pruebas solo con datos ficticios.'),
  ('PRD_2026', false, true, 'Proyecto normativo 2026 desactivado; RD 889/2022 permanece activo.')
on conflict (code) do update
set enabled = false,
    locked_closed = true,
    reason = excluded.reason,
    updated_at = now();

insert into public.service_catalog (code, name_es, description, price_cents, currency, fictitious)
values
  ('diagnostico-ficticio', 'Diagnostico ficticio', 'Servicio de prueba sin cobro real.', 0, 'EUR', true),
  ('guia-expediente-ficticia', 'Guia de expediente ficticia', 'Precio simulado para validar flujos de pago.', 4900, 'EUR', true)
on conflict (code) do update
set name_es = excluded.name_es,
    description = excluded.description,
    price_cents = excluded.price_cents,
    currency = excluded.currency,
    fictitious = true;

insert into public.presentation_guides (
  code,
  version,
  title,
  variable_data,
  source_url,
  source_verified_at,
  valid_from,
  status
)
values (
  'sede-tasa-107',
  'rd-889-2022-v1',
  'Guia ficticia de presentacion y Tasa 107 separada',
  '{"tasa":"107","paymentSeparatedFromHomologaRevenue":true,"platformDoesNotSubmit":true,"platformDoesNotPayTax":true}'::jsonb,
  'https://www.universidades.gob.es/',
  '2026-08-06T00:00:00Z',
  '2026-08-06',
  'active'
)
on conflict (code, version) do nothing;

insert into public.schema_migrations (version)
values ('0010_closed_pilot_lifecycle')
on conflict (version) do nothing;

commit;
